### ISSUE TITLE
passphrase replaced by hash in account creation page

### ISSUE THREAD

**Issue by Nishogi** [SeaweedbrainCY/zero-totp#107]
**Describe the bug**
My passphrase seems to be replaced by its hash in the account creation page if the account creations fails.

**To Reproduce**
1. Try to create an account with an already used email.
2. Upon getting the error message, you can see the passphrase length changed.
3. By clicking the eye, you can see it was replaced by ... something else. Did not investigate what it really is.

**Expected behavior**
Not changing the fields at all.

**Screenshots**
![image](https://github.com/SeaweedbrainCY/zero-totp/assets/109806378/71f60843-0dd9-4ac5-8877-1386437442d1)

**Desktop (please complete the following information):**
- OS: macOS 14.5 (23F79)
- Browser Arc
- Version 1.47.1 (50893)

**Comment by SeaweedbrainCY** [comment]
This is indeed the first hash version of the passphrase (cf https://docs.zero-totp.com/code_doc/Cryptography/#user-creation-flow)

Will be fixed in the next release. Thanks for the heads up ;)
