### ISSUE TITLE
favicon not showing up when trying to add a new code

### ISSUE THREAD

**Issue by Nishogi** [SeaweedbrainCY/zero-totp#68]
**Describe the bug**
Favicon not showing up, and replaced by a 'missing image' icon

**To Reproduce**
1. Go to 'add a new code'
2. The favicon is not showing up [1]
3. Add a website e.g. github.com 
4. Still no favicon [2]

**Expected behavior**
Either don't show anything or show the favicon of the website

**Screenshots**
[1]![1](https://github.com/SeaweedbrainCY/zero-totp/assets/109806378/1c9bf731-14f9-45fd-9c06-aa27a2b8aafd)

[2]![2](https://github.com/SeaweedbrainCY/zero-totp/assets/109806378/72415b72-b38a-4035-9cbd-099bf03d9294)

**Desktop:**
 - OS: macOS 14.2.1 (23C71)
 - Browser Arc
 - Version 1.27.2 (45664)

**Comment by SeaweedbrainCY** [comment]
UI is misleading 
Will update URI to favicon URI
Name's placeholder from github.com eto GitHub
