### ISSUE TITLE
The burger menu is broken on iOS devices

### ISSUE THREAD

**Issue by bkolonics** [SeaweedbrainCY/zero-totp#7]

**Comment by bkolonics** [comment]
For me it's working fine, could someone confirm ?

**Comment by SeaweedbrainCY** [comment]
Does work on a desktop simulating a mobile but doesn’t work on iOS devices 
 
The bug has been introduced few commits ago 

I will fix it

**Comment by bkolonics** [comment]
Ok, just to add, it also works on android devices.
